apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ca-bundle-injector
  annotations:
    cert-manager.io/inject-ca-from: cert-manager/ca-bundle-injector-webhook.cert-manager.svc
webhooks:
  - name: ca-bundle-injector.cert-manager.svc
    clientConfig:
      service:
        name: ca-bundle-injector-webhook
        namespace: cert-manager
        path: /mutate
        port: 443
    rules:
      - apiGroups: ["*"]
        apiVersions: ["*"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
        scope: "Namespaced"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
