---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ca-bundle-injector-webhook-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ca-bundle-injector-webhook-pod-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ca-bundle-injector-webhook-pod-reader
subjects:
  - kind: ServiceAccount
    name: ca-bundle-injector-webhook
    namespace: cert-manager