apiVersion: v1
kind: Service
metadata:
  name: ca-bundle-injector-webhook
  namespace: cert-manager
  labels:
    app: ca-bundle-injector-webhook
spec:
  ports:
  - port: 443
    targetPort: 8443
    name: tls
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: ca-bundle-injector
